[package]
name = "v8_learning"
version = "0.1.0"
edition = "2021"


[dependencies]
v8 = "0.41"
serde_v8 = "0.37.0"
serde_json = "1"
reqwest = { version = "0.11", features = ["blocking"]}

[workspace]
